### ISSUE TITLE
some question about calulate socre？

### ISSUE THREAD

**Issue by smashfan** [princeton-nlp/LESS#14]
```
N_SUBTASKS = {"mmlu": 57, "bbh": 27, "tydiqa": 9} 
influence_score = influence_score.reshape(
            influence_score.shape[0], N_SUBTASKS[target_task_name], `-1).mean(-1).max(-1)[0]
```

what is meaning N_SUBTASKS ,  why do this?      Can I change it to  "  influence_score =influence_score.mean(-1)[0]" ?

**Comment by xiamengzhou** [comment]
In our experiments, all the tasks we utilized possessed an inherent substructure. If your validation data lacks this substructure, you can simply set N_SUBTASKS[your_task] = 1, and it should work with the code!
