### ISSUE TITLE
OOM Errors in Step 3.1

### ISSUE THREAD

**Issue by ChangyuChen347** [princeton-nlp/LESS#20]
Hello, I encounter an Out of Memory error at step 3.1. My configuration includes a single A100 GPU with 80GB of memory. Reducing the max_length to 128 allows me to avoid the OOM error. I would like to know if this is a reasonable approach and if there are any other methods to resolve this issue.

Here is the command I am using:
CUDA_VISIBLE_DEVICES=0 python3 -m less.data_selection.get_info \
 --task $task \
 --info_type grads \
 --model_path $model \
 --output_path $output_path \
 --gradient_projection_dimension $dims \
 --gradient_type sgd \
 --data_dir $data_dir \
 --max_length 128

**Comment by Haruka1307** [comment]
I met the same error.Check your log ,do you import fast_jl successfully? If it prints "Use basic projector " then fast_jl didn't import actually.When generating eval_grads, cuda number 0 was used, and the model&dataloader preempted the graphics memory, resulting in an OOM error during loss calculation.You may move the grads to another available in collect_grad_reps.py;
<img width="821" alt="image" src="https://github.com/princeton-nlp/LESS/assets/67563838/69216544-dbd1-4f86-abc7-4916a822bc4e">

**Comment by Haruka1307** [comment]
I met the same error.Check your log ,do you import fast_jl successfully? If it prints "Use basic projector " then fast_jl didn't import actually.When generating eval_grads, cuda number 0 was used, and the model&dataloader preempted the graphics memory, resulting in an OOM error during loss calculation.You may move the grads to another available in collect_grad_reps.py;
<img width="821" alt="image" src="https://github.com/princeton-nlp/LESS/assets/67563838/69216544-dbd1-4f86-abc7-4916a822bc4e">

**Comment by ChangyuChen347** [comment]
> I met the same error.Check your log ,do you import fast_jl successfully? If it prints "Use basic projector " then fast_jl didn't import actually.When generating eval_grads, cuda number 0 was used, and the model&dataloader preempted the graphics memory, resulting in an OOM error during loss calculation.You may move the grads to another available in collect_grad_reps.py; <img alt="image" width="821" src="https://private-user-images.githubusercontent.com/67563838/337597375-69216544-dbd1-4f86-abc7-4916a822bc4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTE5MTMsIm5iZiI6MTcxNzc1MTYxMywicGF0aCI6Ii82NzU2MzgzOC8zMzc1OTczNzUtNjkyMTY1NDQtZGJkMS00Zjg2LWFiYzctNDkxNmE4MjJiYzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA5MTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZjEzMWVjNWFjYzY3MzZhNTExMDdhNGRjNTM3NzI0ZjdjZDBmZDEzNWYxMTAzODM4MjI3Y2E1NWE3MWFhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.guqJfaCy2tt7g8ueP1UTweD7mI9VdxSPKDWGMYPLKJ4">

Thanks. After using the CUDA projector, there are no more OOM issues

**Comment by DDrShieh** [comment]
@Haruka1307  Have you ever fixed this issue before OOM in step 3.1 ? https://github.com/princeton-nlp/LESS/issues/19#issue-2317088583
Your solution doesn't work in this situation. Any advice for this?
