### ISSUE TITLE
Question about influence scoring (regarding cosine-similarity)

### ISSUE THREAD

**Issue by DSKSD** [princeton-nlp/LESS#24]
Hi, thank you for the great work!

I found the actual implementation of the influence scoring is performed via just inner-product instead of the cosine similarity as in described in Section 3.2 (Adam Influence).
https://github.com/princeton-nlp/LESS/blob/main/less/data_selection/matching.py#L39

I could not find any normalization term for the gradient vectors. Did I misunderstand something?

**Comment by qrdai** [comment]
I think the normalization is done when the gradient files are merged and saved here: https://github.com/princeton-nlp/LESS/blob/main/less/data_selection/collect_grad_reps.py#L285

So in the matching step only dot product is needed.

**Comment by DSKSD** [comment]
@qrdai Oh, I missed it! Thank you for your response!
