### ISSUE TITLE
data selection results

### ISSUE THREAD

**Issue by wang-debug** [princeton-nlp/LESS#6]
Thank you very much for your work!
i hope it's not too forward to ask if you could share the datasets obtained during the third step of data selection. I believe it could help reduce costs.

**Comment by xiamengzhou** [comment]
Hi! Sorry for the late reply. [less-data.zip](https://huggingface.co/datasets/princeton-nlp/less_data/tree/main) contains the selected data in the subfolder `selected_data`. Could you check it out?

**Comment by wang-debug** [comment]
Thank you for your sharing!
